// Generated by @stalkerg/svelte-icu. Do not edit.

declare namespace SvelteIcu {
  interface LocaleRegistry {
    readonly "en": true;
    readonly "ja": true;
  }

  interface MessageRegistry {
    readonly "greeting": {
      readonly "name": unknown;
    };
    readonly "items": {
      readonly "count": number;
    };
    readonly "language": import("@stalkerg/precompile-intl-runtime").NoMessageValues;
  }
}
