import { parseSync } from '@babel/core';
import { analyzeMessage } from '@stalkerg/babel-plugin-precompile-intl';

const RUNTIME_PACKAGE = '@stalkerg/precompile-intl-runtime';

function fail(filename, message) {
  throw new Error(`[svelte-icu] Cannot generate types for ${filename}: ${message}`);
}

function propertyName(property, filename) {
  if (property.computed) fail(filename, 'computed translation keys are not supported.');
  if (property.key.type === 'Identifier' || property.key.type === 'StringLiteral') {
    return property.key.name ?? property.key.value;
  }
  fail(filename, 'translation keys must be identifiers or strings.');
}

function messageText(node, filename, key) {
  if (node.type === 'StringLiteral') return node.value;
  if (node.type === 'TemplateLiteral' && node.expressions.length === 0) {
    return node.quasis[0]?.value.raw ?? '';
  }
  fail(filename, `translation ${JSON.stringify(key)} must be a static string.`);
}

function extractMessages(source, filename) {
  const ast = parseSync(source, {
    filename,
    sourceType: 'module',
    parserOpts: {
      plugins: filename.endsWith('.ts') || filename.endsWith('.mts') ? ['typescript'] : [],
    },
  });
  const exported = ast?.program.body.find((node) => node.type === 'ExportDefaultDeclaration');
  if (!exported || exported.type !== 'ExportDefaultDeclaration') {
    fail(filename, 'the locale module must have a default export.');
  }
  if (exported.declaration.type !== 'ObjectExpression') {
    fail(filename, 'the default export must be an object.');
  }

  const messages = new Map();
  function visit(object, prefix = '') {
    for (const property of object.properties) {
      if (property.type !== 'ObjectProperty') {
        fail(filename, 'locale objects cannot contain spreads or methods.');
      }
      const ownName = propertyName(property, filename);
      const key = prefix ? `${prefix}.${ownName}` : ownName;
      if (property.value.type === 'ObjectExpression') {
        visit(property.value, key);
      } else {
        messages.set(key, messageText(property.value, filename, key));
      }
    }
  }
  visit(exported.declaration);
  return messages;
}

function argumentType(types) {
  // A numeric use is compatible with both interpolation and Date's numeric timestamp form.
  if (types.has('number')) return 'number';
  if (types.has('date')) return 'Date | number';
  return 'unknown';
}

function virtualModuleDeclaration(prefix) {
  return [
    `declare module ${JSON.stringify(prefix)} {`,
    `  export type Locale = import(${JSON.stringify(RUNTIME_PACKAGE)}).Locale;`,
    `  export type MessageKey = import(${JSON.stringify(RUNTIME_PACKAGE)}).MessageKey;`,
    `  export type MessageValuesFor<Key extends MessageKey> = import(${JSON.stringify(RUNTIME_PACKAGE)}).MessageValuesFor<Key>;`,
    `  export const availableLocales: readonly Locale[];`,
    `  export const catalogs: Readonly<Partial<Record<Locale, import(${JSON.stringify(RUNTIME_PACKAGE)}).Catalog>>>;`,
    `  export const loaders: Readonly<Partial<Record<Locale, () => Promise<import(${JSON.stringify(RUNTIME_PACKAGE)}).Catalog>>>>;`,
    `}`,
  ];
}

export function generateTypeDeclarations(localeModules, prefix = '$locales') {
  const locales = localeModules
    .map(({ locale }) => locale)
    .sort((left, right) => {
      const specificity = left.split('-').length - right.split('-').length;
      return specificity || left.localeCompare(right, 'en');
    });
  const messages = new Map();

  for (const { source, filename } of localeModules) {
    for (const [key, message] of extractMessages(source, filename)) {
      let argumentsByName = messages.get(key);
      if (!argumentsByName) {
        argumentsByName = new Map();
        messages.set(key, argumentsByName);
      }
      for (const [name, types] of Object.entries(analyzeMessage(message))) {
        let mergedTypes = argumentsByName.get(name);
        if (!mergedTypes) {
          mergedTypes = new Set();
          argumentsByName.set(name, mergedTypes);
        }
        for (const type of types) mergedTypes.add(type);
      }
    }
  }

  const lines = [
    '// Generated by @stalkerg/svelte-icu. Do not edit.',
    '',
    'declare namespace SvelteIcu {',
    '  interface LocaleRegistry {',
    ...locales.map((locale) => `    readonly ${JSON.stringify(locale)}: true;`),
    '  }',
    '',
    '  interface MessageRegistry {',
  ];

  for (const key of [...messages.keys()].sort()) {
    const argumentsByName = messages.get(key);
    if (argumentsByName.size === 0) {
      lines.push(
        `    readonly ${JSON.stringify(key)}: import(${JSON.stringify(RUNTIME_PACKAGE)}).NoMessageValues;`,
      );
      continue;
    }
    lines.push(`    readonly ${JSON.stringify(key)}: {`);
    for (const name of [...argumentsByName.keys()].sort()) {
      lines.push(
        `      readonly ${JSON.stringify(name)}: ${argumentType(argumentsByName.get(name))};`,
      );
    }
    lines.push('    };');
  }

  lines.push('  }', '}');
  if (prefix !== '$locales') lines.push('', ...virtualModuleDeclaration(prefix));
  return `${lines.join('\n')}\n`;
}
